### PR TITLE
tweaks to city

### PR DESCRIPTION
**Pull request by etet2**
-made barricades be dissasemblable with crowbars
-adjusted barricade postition to force action into the middle rather than left flank
-reinforced and added defences on soviet side(mostly left flank)

### CODE REVIEW

**Comment by Eddyskingdom** [comment]
is this testid and compiled also make it so it takes 20 seconds to break it down

**Comment by etet2** [comment]
i feel like 20 is too much, because it will be inpractial druing fighting and it's much safer to shoot it, wich makes engineers pretty useless(i was trying to give engineers use as they are pretty useless after the grace period ends)

**Comment by Eddyskingdom** [comment]
fine make it 10 and i will merge it

**Comment by etet2** [comment]
done

**Pull request merged**
