### PR TITLE
Commenting out unused code

### PR DESCRIPTION
**Pull request by Jeff-Dome**
when has police or medical or any kind of these tapes been used, never is when but likewise, it's just blotting the code for no reason

### CODE REVIEW

**Comment by KanohaShinobi** [comment]
better to not touch it, lots of leben code relies on the space stuff. Leave the code alone unless removing ww2 stuff thats unused. Like brains or tactics.

**Comment by Harcourt1** [comment]
Well hold on there, removing all SS13 assets is a good first step. I really want to slim the codebase to ww2 only. Can you verify that it doesn't break any maps and then i'll merge.

**Comment by Jeff-Dome** [comment]
let see, i'll boot it locally

**Comment by Jeff-Dome** [comment]
Shit, forgot i was on the wrong branch with my admin file

**Comment by Jeff-Dome** [comment]
No Issues with maps currently

**Comment by Harcourt1** [comment]
Great commit, thanks man! Whats your discord name?

**Comment by Jeff-Dome** [comment]
Big gay

**Pull request merged**
