### PR TITLE
Parachute , Canned food and some Stuff.

### PR DESCRIPTION
**Pull request by Leonister**
- Canned Food : Heinz (Tomato Soup), Scho Ka Kola (Chocolate), MRE , Canned Sardine and SPAM , and added a Atika Cigars (German)
- a Barrel for use like a light source (can be lit)
- Fallschirmjager (German Parachute) , backpack sprites and using (falling and disamble)

### CODE REVIEW

**Comment by kachnov** [comment]
conflicts

**Comment by kachnov** [comment]
I'll fix the conflicts in cigarettes.dmi

**Comment by Leonister** [comment]
Do it

**Comment by kachnov** [comment]
@Leonister manually merged cigarette.dmi changes. Remove the file and I'll merge the PR.

**Pull request merged**
